#!/usr/bin/env bash

# Self-healing symlink structure
# Source once - ensures entire symlink farm is correct
# Skips gracefully if directories don't exist

#--[CLEANUP]------------------------------------

cleanup_broken_links() {
    local dirs=("$HOME/bin" "$HOME/bin/lib" "$HOME/bin/sys" "$HOME/.local/share" "$HOME/.local/bin")
    for dir in "${dirs[@]}"; do
        # A missing dir is normal (e.g. $HOME/bin/sys before setup_sys ever ran) -
        # skip it quietly. Once the dir exists, a real find/-delete failure (e.g.
        # permission denied) is no longer swallowed.
        [ -d "$dir" ] || continue
        find "$dir" -maxdepth 1 -xtype l -delete
    done
}

cleanup_empty_home_symlinks() {
    for link in "$HOME"/*/; do
        [ -L "${link%/}" ] || continue
        # Skip wormholes - they're managed by the wormhole command
        [[ "$(basename "${link%/}")" == "wormhole" ]] && continue
        local target
        target=$(readlink -f "${link%/}")
        [ -d "$target" ] || continue

        local listing
        if listing=$(ls -A "$target" 2>&1); then
            [ -z "$listing" ] && rm "${link%/}"
        else
            # Couldn't read $target (e.g. permission denied) - do NOT treat that
            # as "empty"; removing the link on unreadable output would be a guess.
            echo "symlink-farm: cannot read $target - leaving ${link%/}" >&2
        fi
    done
}

cleanup_broken_links
cleanup_empty_home_symlinks

#--[UTILITIES]----------------------------------

setup_sys() {
    local user_dir="$1"
    [ -d "$user_dir" ] || return 0
    mkdir -p "$user_dir/sys"
}

LINK_PROBE_NAME=".lushrc-link-probe"   # transient; removed before supports_symlinks returns

# Some filesystems accept writes but reject symlink(2) outright — Android's FUSE
# shared storage is the case that forced this. Probe the capability, not the
# platform, so no host ever needs special-casing here.
supports_symlinks() {
    local dir="$1"
    local probe="$dir/$LINK_PROBE_NAME.$$"

    [ -d "$dir" ] || return 1
    ln -s "$dir" "$probe" 2>/dev/null || return 1
    rm -f "$probe"
}

link_contents() {
    local source_dir="$1"
    local target_dir="$2"

    [ -d "$source_dir" ] || return 0

    for item in "$source_dir"/*; do
        [ -e "$item" ] || continue
        [ -d "$item" ] && continue
        ln -sf "$item" "$target_dir/$(basename "$item")"
    done
}

sync_tool_stubs() {
    local lib_dir="$BASHRC/bin/lib"
    [ -d "$lib_dir" ] || return 0

    local main tool_dir tool stub
    for main in "$lib_dir"/*/main.sh; do
        [ -f "$main" ] || continue
        tool_dir="$(dirname "$main")"
        tool="$(basename "$tool_dir")"
        stub="$BASHRC/bin/$tool"

        [ -e "$stub" ] && continue

        cat > "$stub" <<STUB
#!/usr/bin/env bash
# Auto-generated by symlink-farm.sh — do not edit.
# Implementation: bin/lib/$tool/main.sh
LUSH_ROOT="\${BASHRC:-\$(dirname "\$(dirname "\$(realpath "\${BASH_SOURCE[0]}")")")}"
MAIN="\$LUSH_ROOT/bin/lib/$tool/main.sh"
[[ -r "\$MAIN" ]] || "\$LUSH_ROOT/bin/lush" install "$tool" || exit 1
exec bash "\$MAIN" "\$@"
STUB
        chmod +x "$stub"
        echo "symlink-farm: generated stub bin/$tool -> bin/lib/$tool/main.sh"
    done
}

link_contents_sudo() {
    local source_dir="$1"
    local target_dir="$2"

    [ -d "$source_dir" ] || return 0

    for item in "$source_dir"/*; do
        [ -e "$item" ] || continue
        [ -d "$item" ] && continue
        sudo ln -sf "$item" "$target_dir/$(basename "$item")"
    done
}

sync_system_links() {
    link_contents_sudo "$HOME/bin/sys" "/usr/local/bin"
    link_contents_sudo "/home/linuxbrew/.linuxbrew/bin" "/usr/local/bin"
    link_contents_sudo "$HOME/.config/systemd/sys" "/etc/systemd/system"
    link_contents_sudo "$HOME/.config/autostart/sys" "/etc/xdg/autostart"
    link_contents_sudo "$HOME/.local/share/applications/sys" "/usr/share/applications"
    sudo systemctl daemon-reload
}

#--[BIN]----------------------------------------

sync_tool_stubs

setup_sys "$HOME/bin"
ln -sfn "$HOME/.local/bin" "$HOME/bin/local"
link_contents "$TOOLS/bin" "$HOME/bin"
link_contents "$PROJECTS/scripts" "$HOME/bin"
# $BASHRC/bin is now in PATH directly - no symlinks needed
link_contents "$TOOLS/bin/lib" "$HOME/bin/lib"
link_contents "$BASHRC/bin/lib" "$HOME/bin/lib"

# UV tools → ~/.local/bin
if command -v uv &>/dev/null; then
    for tool_bin in "$HOME/.local/share/uv/tools"/*/bin/*; do
        [ -x "$tool_bin" ] || continue
        ln -sf "$tool_bin" "$HOME/.local/bin/$(basename "$tool_bin")"
    done
fi

#--[SYSTEMD]------------------------------------

if [ -d "$HOME/.config/systemd" ]; then
    setup_sys "$HOME/.config/systemd"
    [ -L "$HOME/.config/systemd/user" ] || ln -sf . "$HOME/.config/systemd/user"
fi
link_contents "$BASHRC/storage/services" "$HOME/.config/systemd"

for svc in "$BASHRC/storage/services"/*.service; do
    [ -f "$svc" ] || continue
    name=$(basename "$svc")
    if ! systemctl --user is-enabled "$name" &>/dev/null; then
        systemctl --user enable "$name" || echo "symlink-farm: failed to enable $name" >&2
    fi
done

#--[AUTOSTART]----------------------------------

setup_sys "$HOME/.config/autostart"

#--[XDG]----------------------------------------

ln -sf "$BASHRC/modules/universal/xdg.sh" "$HOME/.config/user-dirs.dirs"

#--[FONTS]--------------------------------------

[ -d "$HOME/.config/fonts" ] && ln -sfn "$HOME/.config/fonts" "$HOME/.local/share/fonts"

#--[NIX APPLICATIONS]-------------------------------

link_contents "$HOME/.nix-profile/share/applications" "$HOME/.local/share/applications"

#--[MEDIA GALLERY]-------------------------------

# Every sync below builds symlinks under $MEDIA. Decide once whether that is even
# possible; without this the whole media section fails silently per-file.
MEDIA_LINKS_OK=true
if [ -d "$MEDIA" ] && ! supports_symlinks "$MEDIA"; then
    MEDIA_LINKS_OK=false
    echo "symlink-farm: $MEDIA rejects symlinks - skipping gallery, wallpapers, screenshot and workspace crosslinks" >&2
fi

# $MEDIA and $wpp_dir may themselves be symlinks (Termux points $MEDIA at Android
# shared storage). find does not descend into a symlinked path operand, so every
# find below needs the trailing slash to force it.
#
# sync_media_gallery additionally has to walk through deliberate *top-level*
# pointers under $MEDIA (Termux: $MEDIA/.storage -> real storage elsewhere) while
# never walking through symlinks deeper in the tree (real depth-2 links such as
# $MEDIA/krita/workspace -> $WORKSPACE/krita must NOT be indexed). No find below
# ever uses -L, and the one dereference that happens is done explicitly, once,
# against $MEDIA's own immediate children - there is no recursive follow step for
# a loop to occur through. Do not "helpfully" add loop detection.

# Links one already-classified file into its gallery by extension.
_gallery_link() {
    local file="$1" name="$2"
    local ext="${file##*.}"
    case "${ext,,}" in
        png|jpg|jpeg|gif|webp|svg|tiff|tif|bmp|kra|xcf|psd)
            ln -sf "$file" "$PICTURES_GALLERY/$name" ;;
        mp4|mkv|webm|mov|avi|mpeg|mpg|flv|wmv)
            ln -sf "$file" "$VIDEOS_GALLERY/$name" ;;
        mp3|flac|wav|ogg|opus|aac|m4a|wma)
            ln -sf "$file" "$AUDIO_GALLERY/$name" ;;
    esac
}

# Scans one root (non-recursively-through-symlinks) for gallery-eligible files.
# $name_prefix is stripped from each match to build the gallery entry name -
# passing $MEDIA preserves today's naming for $MEDIA's own subdirectories;
# passing a resolved top-level-pointer target makes files under it name as
# though that root were $MEDIA itself (no leading ".storage-"/"storage-").
_gallery_scan_root() {
    local root="$1" name_prefix="$2"

    while IFS= read -r -d '' file; do
        local rel="${file#$name_prefix/}"
        local name="${rel//\//-}"
        _gallery_link "$file" "$name"
    # Exclusions anchor to the root being scanned, not to $MEDIA: a pointer target
    # carries its own gallery/screenshots/wallpapers subtrees (Termux's shared
    # storage does), and $MEDIA-anchored patterns would never match them.
    done < <(find "$root/" \
        -not -path "$root/gallery/*" \
        -not -ipath "$root/screenshots/*" \
        -not -ipath "$root/wallpapers/*" \
        -not -ipath "$root/wallpaper/*" \
        -not -ipath "$root/wpp/*" \
        -type f -print0)
}

sync_media_gallery() {
    [ -d "$MEDIA" ] || return 0
    [ "$MEDIA_LINKS_OK" = true ] || return 0

    # Clear existing symlinks (real files untouched)
    find "$PICTURES_GALLERY" "$VIDEOS_GALLERY" "$AUDIO_GALLERY" "$WALLPAPERS_GALLERY" \
        -maxdepth 1 -type l -delete 2>/dev/null || true

    local media_resolved
    media_resolved=$(readlink -f "$MEDIA")

    # $MEDIA's own tree (ordinary subdirectories only - see loop-safety note above)
    _gallery_scan_root "$MEDIA" "$MEDIA"

    # Deliberate top-level pointers: dereference exactly one level. Skip anything
    # that resolves back inside $MEDIA (would duplicate an entry already reachable
    # directly - e.g. the screenshot.<ext> -> screenshots/latest.<ext> link
    # sync_latest_screenshot creates), report and skip anything dangling, and
    # dedupe two pointers that resolve to the same target.
    local seen_targets=("$media_resolved")
    local entry
    while IFS= read -r -d '' entry; do
        [ "$(basename "$entry")" = "gallery" ] && continue

        local resolved
        resolved=$(readlink -f "$entry")

        # Check "resolves inside $MEDIA" before "resolves to a directory": a
        # target like screenshots/latest.png (sync_latest_screenshot's own link)
        # resolves to a FILE, not a dir, but it must be silently skipped as an
        # in-tree duplicate, not reported as dangling.
        case "$resolved" in
            "$media_resolved"|"$media_resolved"/*) continue ;;
        esac

        if [ -z "$resolved" ] || [ ! -d "$resolved" ]; then
            echo "symlink-farm: gallery root $entry does not resolve to a directory - skipping" >&2
            continue
        fi

        local seen already_seen=false
        for seen in "${seen_targets[@]}"; do
            [ "$seen" = "$resolved" ] && already_seen=true && break
        done
        [ "$already_seen" = true ] && continue
        seen_targets+=("$resolved")

        _gallery_scan_root "$resolved" "$resolved"
    done < <(find "$MEDIA/" -maxdepth 1 -type l -print0)
}

sync_media_gallery

#--[WALLPAPERS GALLERY]--------------------------

sync_wallpapers_gallery() {
    local wpp_dir=""
    for _d in wallpapers Wallpapers wallpaper Wallpaper wpp Wpp; do
        [ -d "$MEDIA/$_d" ] && wpp_dir="$MEDIA/$_d" && break
    done
    [ -n "$wpp_dir" ] || return 0
    [ "$MEDIA_LINKS_OK" = true ] || return 0

    mkdir -p "$WALLPAPERS_GALLERY"

    while IFS= read -r -d '' file; do
        local rel="${file#$wpp_dir/}"
        local name="${rel//\//-}"
        ln -sf "$file" "$WALLPAPERS_GALLERY/$name"
    done < <(find "$wpp_dir/" -type f -print0)
}

sync_wallpapers_gallery

#--[LATEST SCREENSHOT]---------------------------

SCREENSHOT_SOURCE_BASE="latest"        # $MEDIA/screenshots/<base>.<ext> written by the capture keybind
SCREENSHOT_LINK_BASE="screenshot"      # $MEDIA/<base>.<ext>
SCREENSHOT_GALLERY_BASE="latest-screenshot"

sync_latest_screenshot() {
    [ -d "$MEDIA" ] || return 0
    [ "$MEDIA_LINKS_OK" = true ] || return 0

    local screenshot_src=""
    for candidate in "$MEDIA/screenshots/$SCREENSHOT_SOURCE_BASE".*; do
        [ -f "$candidate" ] || continue
        screenshot_src="$candidate"
        break
    done

    # Drop links from a previous capture format so only one survives. $MEDIA is
    # already known to exist above, so a failure here is real and must surface.
    find "$MEDIA/" -maxdepth 1 -type l -name "$SCREENSHOT_LINK_BASE.*" -delete

    [ -n "$screenshot_src" ] || return 0
    local ext="${screenshot_src##*.}"

    # Link to media root for quick access
    ln -sf "$screenshot_src" "$MEDIA/$SCREENSHOT_LINK_BASE.$ext"

    # Link to pictures gallery — screenshots/ is excluded from sync_media_gallery,
    # and $MEDIA/<link>.<ext> is a symlink, so this is the only gallery entry for it
    [ -d "$PICTURES_GALLERY" ] && ln -sf "$screenshot_src" "$PICTURES_GALLERY/$SCREENSHOT_GALLERY_BASE.$ext"
}

sync_latest_screenshot

#--[WORKSPACE ↔ MEDIA CROSSLINKS]---------------

sync_workspace_media() {
    [ -d "$WORKSPACE" ] || return 0
    [ -d "$MEDIA" ] || return 0
    # Both directions are needed for a crosslink to mean anything, and the media
    # side is the one that can be unwritable - so it's all or nothing.
    [ "$MEDIA_LINKS_OK" = true ] || return 0

    for ws_dir in "$WORKSPACE"/*/ "$WORKSPACE"/*/*/; do
        [ -d "$ws_dir" ] || continue
        local rel="${ws_dir%/}"; rel="${rel#$WORKSPACE/}"
        local media_dir="$MEDIA/$rel"
        [ -d "$media_dir" ] || continue

        # Workspace side: media/ or local-media/ → Media/project
        local ws_link="${ws_dir%/}/media"
        if [ -e "$ws_link" ] && [ ! -L "$ws_link" ]; then
            ws_link="${ws_dir%/}/local-media"
        fi
        ln -sfn "$media_dir" "$ws_link"

        # Media side: workspace/ → Workspace/project
        ln -sfn "${ws_dir%/}" "$media_dir/workspace"
    done
}

sync_workspace_media

